name: Create new tag
description: 'This action gets the new tag version and push it to repository'

inputs:
    version:
        description: 'the new version to create'
        required: true
    owner:
        description: 'repository owner (github''s username)'
        required: true
    github_token:
        description: 'Github token'
        required: true

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.owner }}
        - ${{ inputs.github_token }}
        - ${{ inputs.version }}